library CqlAllInOne version '1'
/*
define AbsNull: Abs(null as Integer)
define Add11: 1 + 1
define TestAfterNull: null as Integer after IntegerIntervalTest
define IntegerIntervalTest: Interval[1, 10]
define AllTrueAllTrue : AllTrue({true,true})
define TrueAndTrue : true and true
define AnyTrueAllTrue               : AnyTrue({true,true})
define AnyTrueAllFalse              : AnyTrue({false,false})
*/
define AsQuantity: 45.5 'g' as Quantity
//define CastAsQuantity: cast 45.5 'g' as Quantity
//define AsDateTime: DateTime(2014, 01, 01) as DateTime

