package org.cqframework.cql.cql2elm.utils

import org.cqframework.cql_to_elm.BuildConfig

internal fun getTranslatorVersion(): String {

    // On the JVM, it's possible to query Package.implementationVersion like this:
    // val translatorVersion =
    // org.cqframework.cql.cql2elm.LibraryBuilder::class.java.getPackage().implementationVersion
    // In KMP, BuildConfig is needed (generated by the build process).

    return BuildConfig.IMPLEMENTATION_VERSION
}
