coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1% # this covers slighty flaky tests
        paths:
          - "Src/java"
    patch:
      default:
        # basic
        target: 80
        threshold: 0%
        base: auto
        # advanced
        branches:
          - master
        if_ci_failed: error #success, failure, error, ignore
        only_pulls: false
        paths:
          - "Src/java"