library ValueLiteralsAndSelectors version '1'

context Unfiltered

//null
define Null : null

//Boolean
define BooleanFalse  : false
define BooleanTrue  : true

//integer
define IntegerZero  : 0
define IntegerPosZero  : +0
define IntegerNegZero  : -0
define IntegerOne  : 1
define IntegerPosOne  : +1
define IntegerNegOne  : -1
define IntegerTwo  : 2
define IntegerPosTwo  : +2
define IntegerNegTwo  : -2
define Integer10Pow9  : 1000000000
define IntegerPos10Pow9  : +1000000000
define IntegerNeg10Pow9  : -1000000000
define Integer2Pow31ToZero1IntegerMaxValue  : 2147483647
define IntegerPos2Pow31ToZero1IntegerMaxValue  : +2147483647
define IntegerNeg2Pow31ToZero1  : -2147483647
define Integer2Pow31  : 2147483648
define IntegerPos2Pow31  : +2147483648
define IntegerNeg2Pow31IntegerMinValue  : -2147483648
define Integer2Pow31ToInf1  : 2147483649
define IntegerPos2Pow31ToInf1  : +2147483649
define IntegerNeg2Pow31ToInf1  : -2147483649

//decimal
define DecimalZero  : 0.0
define DecimalPosZero  : +0.0
define DecimalNegZero  : -0.0
define DecimalOne  : 1.0
define DecimalPosOne  : +1.0
define DecimalNegOne  : -1.0
define DecimalTwo  : 2.0
define DecimalPosTwo  : +2.0
define DecimalNegTwo  : -2.0
define Decimal10Pow9  : 1000000000.0
define DecimalPos10Pow9  : +1000000000.0
define DecimalNeg10Pow9  : -1000000000.0
define Decimal2Pow31ToZero1  : 2147483647.0
define DecimalPos2Pow31ToZero1  : +2147483647.0
define DecimalNeg2Pow31ToZero1  : -2147483647.0
define Decimal2Pow31  : 2147483648.0
define DecimalPos2Pow31  : +2147483648.0
define DecimalNeg2Pow31  : -2147483648.0
define Decimal2Pow31ToInf1  : 2147483649.0
define DecimalPos2Pow31ToInf1  : +2147483649.0
define DecimalNeg2Pow31ToInf1  : -2147483649.0
define DecimalZeroStep  : 0.00000000
define DecimalPosZeroStep  : +0.00000000
define DecimalNegZeroStep  : -0.00000000
define DecimalOneStep  : 0.00000001
define DecimalPosOneStep  : +0.00000001
define DecimalNegOneStep  : -0.00000001
define DecimalTwoStep  : 0.00000002
define DecimalPosTwoStep  : +0.00000002
define DecimalNegTwoStep  : -0.00000002
define DecimalTenStep  : 0.0000001
define DecimalPosTenStep  : +0.0000001
define DecimalNegTenStep  : -0.0000001
define DecimalTenthStep  : 0.000000001
define DecimalPosTenthStep  : +0.000000001
define DecimalNegTenthStep  : -0.000000001
define DecimalMaxValue : 9999999999999999999999999999.99999999
define DecimalPosMaxValue : +9999999999999999999999999999.99999999
define DecimalMinValue: -9999999999999999999999999999.99999999

define QuantityZero: 0 'g'
define QuantityPosZero: +0 'g'
define QuantityNegZero: -0 'g'
define QuantityOne: 1.0 'g'
define QuantityPosOne: +1.0 'g'
define QuantityNegOne: -1.0 'g'
define QuantitySmall: 0.05 'mg'
define QuantityPosSmall: +0.05 'mg'
define QuantityNegSmall: -0.05 'mg'
define QuantityStep: 0.00000001 'mg'
define QuantityPosStep: +0.00000001 'mg'
define QuantityNegStep: -0.00000001 'mg'
define QuantityMax: 9999999999999999999999999999.99999999 'mg'
define QuantityPosMax: +9999999999999999999999999999.99999999 'mg'
define QuantityMin: -9999999999999999999999999999.99999999 'mg'

