define YearLiteral: @2014
define UTCYearLiteral: @2014Z
define YearMonthLiteral: @2014-12
define UTCYearMonthLiteral: @2014-12Z
define DateLiteral: @2014-01-31
define UTCDateLiteral: @2014-01-31Z
define HourLiteral: @T23
define UTCHourLiteral: @T23Z
define TimeZoneHourLiteral: @T23-07:00
define TimeZonePositiveHourLiteral: @T23+07:00
define HourMinuteLiteral: @T10:30
define UTCHourMinuteLiteral: @T10:30Z
define TimeZoneHourMinuteLiteral: @T10:30-07:00
define TimeZonePositiveHourMinuteLiteral: @T10:30+07:00
define HourMinuteSecondLiteral: @T10:30:15
define UTCHourMinuteSecondLiteral: @T10:30:15Z
define TimeZoneHourMinuteSecondLiteral: @T10:30:15-07:00
define TimeZonePositiveHourMinuteSecondLiteral: @T10:30:15+07:00
define TimeLiteral: @T10:30:15.0000
define UTCTimeLiteral: @T10:30:15.0000Z
define TimeZoneTimeLiteral: @T10:30:15.0000-07:00
define TimeZonePositiveTimeLiteral: @T10:30:15.0000+07:00
define DateHourLiteral: @2014-02-12T23
define UTCDateHourLiteral: @2014-02-12T23Z
define TimeZoneDateHourLiteral: @2014-02-12T23-07:00
define TimeZonePositiveDateHourLiteral: @2014-02-12T23+07:00
define DateHourMinuteLiteral: @2014-02-12T10:30
define UTCDateHourMinuteLiteral: @2014-02-12T10:30Z
define TimeZoneDateHourMinuteLiteral: @2014-02-12T10:30-07:00
define TimeZonePositiveDateHourMinuteLiteral:@2014-02-12T10:30+07:00
define DateHourMinuteSecondLiteral: @2014-02-12T10:30:15
define UTCDateHourMinuteSecondLiteral: @2014-02-12T10:30:15Z
define TimeZoneDateHourMinuteSecondLiteral: @2014-02-12T10:30:15-07:00
define TimeZonePositiveDateHourMinuteSecondLiteral: @2014-02-12T10:30:15+07:00
define DateTimeLiteral: @2014-02-12T10:30:15.0000
define UTCDateTimeLiteral: @2014-02-12T10:30:15.0000Z
define TimeZoneDateTimeLiteral: @2014-02-12T10:30:15.0000-07:00
define TimeZonePositiveDateTimeLiteral: @2014-02-12T10:30:15.0000+07:00

define YearExpression: 1 year
define YearsExpression: 10 years
define MonthExpression: 1 month
define MonthsExpression: 10 months
define WeekExpression: 1 week
define WeeksExpression: 10 weeks
define DayExpression: 1 day
define DaysExpression: 10 days
define HourExpression: 1 hour
define HoursExpression: 10 hours
define MinuteExpression: 1 minute
define MinutesExpression: 10 minutes
define SecondExpression: 1 second
define SecondsExpression: 10 seconds
define MillisecondExpression: 1 millisecond
define MillisecondsExpression: 10 milliseconds
