/*
@author: Frederic Chopin
@description: Test tags
@allowFluent: true
*/
library TestTags

/*
@author: Frederic Chopin
@description: Test tags
*/
define TestExpression:
  1 + 1

/*
@author: Frederic Chopin
@description: Test tags
*/
define function TestFunction():
  1 + 1

/*
@author: Frederic Chopin
@description: This is a multi-line description that
 spans multiple lines.
@following: true
 */
define TestMultiline:
  1 + 1

/*@:@*/
define TestInvalid:
  1 + 1

