//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.12 at 08:52:42 PM MDT 
//


package org.cqframework.cql.elm.execution;

import org.jvnet.jaxb2_commons.lang.*;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;


/**
 * The BinaryExpression type defines the abstract base type for expressions that take two arguments.
 * 
 * <p>Java class for BinaryExpression complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BinaryExpression"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:hl7-org:elm:r1}Expression"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="operand" type="{urn:hl7-org:elm:r1}Expression" maxOccurs="2" minOccurs="2"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BinaryExpression", namespace = "urn:hl7-org:elm:r1", propOrder = {
    "operand"
})
@XmlSeeAlso({
    And.class,
    Or.class,
    Xor.class,
    Implies.class,
    Equal.class,
    Equivalent.class,
    NotEqual.class,
    Less.class,
    Greater.class,
    LessOrEqual.class,
    GreaterOrEqual.class,
    Add.class,
    Subtract.class,
    Multiply.class,
    Divide.class,
    TruncatedDivide.class,
    Modulo.class,
    Log.class,
    Power.class,
    Indexer.class,
    DurationBetween.class,
    DifferenceBetween.class,
    SameAs.class,
    SameOrBefore.class,
    SameOrAfter.class,
    Contains.class,
    ProperContains.class,
    In.class,
    ProperIn.class,
    Includes.class,
    IncludedIn.class,
    ProperIncludes.class,
    ProperIncludedIn.class,
    Before.class,
    After.class,
    Meets.class,
    MeetsBefore.class,
    MeetsAfter.class,
    Overlaps.class,
    OverlapsBefore.class,
    OverlapsAfter.class,
    Starts.class,
    Ends.class,
    Union.class,
    Intersect.class,
    Except.class,
    Times.class,
    CalculateAgeAt.class
})
public class BinaryExpression
    extends Expression
    implements Equals, HashCode, ToString
{

    @XmlElement(namespace = "urn:hl7-org:elm:r1", required = true)
    protected List<Expression> operand;

    /**
     * Gets the value of the operand property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operand property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Expression }
     * 
     * 
     */
    public List<Expression> getOperand() {
        if (operand == null) {
            operand = new ArrayList<Expression>();
        }
        return this.operand;
    }

    public BinaryExpression withOperand(Expression... values) {
        if (values!= null) {
            for (Expression value: values) {
                getOperand().add(value);
            }
        }
        return this;
    }

    public BinaryExpression withOperand(Collection<Expression> values) {
        if (values!= null) {
            getOperand().addAll(values);
        }
        return this;
    }

    @Override
    public BinaryExpression withAnnotation(Object... values) {
        if (values!= null) {
            for (Object value: values) {
                getAnnotation().add(value);
            }
        }
        return this;
    }

    @Override
    public BinaryExpression withAnnotation(Collection<Object> values) {
        if (values!= null) {
            getAnnotation().addAll(values);
        }
        return this;
    }

    @Override
    public BinaryExpression withLocalId(String value) {
        setLocalId(value);
        return this;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof BinaryExpression)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final BinaryExpression that = ((BinaryExpression) object);
        {
            List<Expression> lhsOperand;
            lhsOperand = (((this.operand!= null)&&(!this.operand.isEmpty()))?this.getOperand():null);
            List<Expression> rhsOperand;
            rhsOperand = (((that.operand!= null)&&(!that.operand.isEmpty()))?that.getOperand():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "operand", lhsOperand), LocatorUtils.property(thatLocator, "operand", rhsOperand), lhsOperand, rhsOperand)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<Expression> theOperand;
            theOperand = (((this.operand!= null)&&(!this.operand.isEmpty()))?this.getOperand():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "operand", theOperand), currentHashCode, theOperand);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            List<Expression> theOperand;
            theOperand = (((this.operand!= null)&&(!this.operand.isEmpty()))?this.getOperand():null);
            strategy.appendField(locator, this, "operand", buffer, theOperand);
        }
        return buffer;
    }
}
