library OpioidCDSCommonConfig version '1.2.3'

define "Chronically on Opioids Enabled":
  true

// Opioid Review Useful
define "Age Less than 18 Years Is Enabled":
  true

// Opioid Review Useful
define "End-Stage Disease Criteria Enabled":
  true

// Active Cancer Treatment
define "Active Cancer Treatment Encounters Condition Is Enabled":
  true

// Active Cancer Treatment
define "Active Cancer Treatment PractitionerRole Specialty Is Enabled":
  false

// Opioid Naive
define "Opioid Naive Prescription Condition Is Enabled":
  true

// Opioid Naive
define "Opioid Naive Report Condition Is Enabled":
  true

// Opioid Naive
define "Opioid Naive Dispense Condition Is Enabled":
  false

// OpioidCDSCommon
define "Hospice Findings Exclusion Enabled":
  false

// Recommendation 2
define "Opioid Treatment Plan Verification Enabled":
  true

// Recommendation 3
define "Opioid Harms & Risks Discussion in Past 90 Days Criteria Enabled":
  true

// Recommendation 6
define "Order is to Treat Acute Pain Enabled":
  true

// Recommendation 8
define "Evidence of Naloxone Enabled":
  true

// Recommendation 9
define "PDMP Data Not Reviewed in Past 90 Days Criteria Enabled":
  true

// Recommendation 12
define "Evidence Based Treatment Criteria For Opioid Use Disorder":
  true
