// Generated by org.cqframework.cql.execution.Engine
(function() {
  var Executor, Library, PatientSource, ctx, lib, measure, psource, result, _ref, CodeService, cservice;


  _ref = require('./cql'), Library = _ref.Library, Executor = _ref.Executor, PatientSource = _ref.PatientSource;

  measure = require('./engine-script');
  lib = new Library(measure);

  importPackage(org.cqframework.cql.execution);
  psource = new PatientSource(Engine.getPatientSource());
  cservice = Engine.getCodeService();
  
  executor = new Executor(lib, cservice);
  result = executor.exec( psource);

  //print(JSON.stringify(result, void 0, 2));
  Engine.add( JSON.stringify(result, void 0, 2) );

}).call(this);
