//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.05 at 11:42:59 AM MST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:hl7-org:elm-modelinfo:r1", xmlns = {
        @XmlNs(prefix = "", namespaceURI = "urn:hl7-org:elm-modelinfo:r1"),
        @XmlNs(prefix = "xsi", namespaceURI = "http://www.w3.org/2001/XMLSchema-instance"),
        @XmlNs(prefix = "xsd", namespaceURI = "http://www.w3.org/2001/XMLSchema")},
        elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.hl7.elm_modelinfo.r1;

import jakarta.xml.bind.annotation.XmlNs;