library ArithmeticFunctions version '1'

context Population

//Abs
define AbsNull: Abs(null)
define Abs0: Abs(0)
define AbsNeg1: Abs(-1)
define AbsNeg1Dec: Abs(-1.0)
define Abs0Dec: Abs(0.0)
define Abs1cm: Abs(-1.0'cm')

//Add
define Add11: 1 + 1
define Add1D1D: 1.0 + 1.0
define Add1Q1Q: 1'g/cm3' + 1'g/cm3'

//Ceiling
define Ceiling1: Ceiling(1)
define Ceiling1D: Ceiling(1.0)
define Ceiling1D1: Ceiling(1.1)
define CeilingNegD1: Ceiling(-0.1)
define CeilingNeg1: Ceiling(-1.0)
define CeilingNeg1D1: Ceiling(-1.1)

//Divide
define Divide10: 1 / 0
define Divide01: 0 / 1
define Divide11: 1 / 1
define Divide1d1d: 1.0 / 1.0
define Divide1Q1: 1'g/cm3' / 1.0
define Divide1Q1Q: 1'g/cm3' / 1'g/cm3'

//Floor

//Exp

//Log

//Ln

//Maximum

//Minimum

//Modulo

//Multiply
define Multiply11 : 1 * 1

//Negate

//Predecessor

//Power

//Round

//Subtract
define Subtract11 : 1 - 1

//Successor

//Truncate

//Truncated Divide
