import com.strumenta.antlrkotlin.gradle.AntlrKotlinTask
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

buildscript { dependencies { classpath("org.slf4j:slf4j-simple:1.7.36") } }

plugins {
    id("cql.kotlin-multiplatform-conventions")
    id("com.strumenta.antlr-kotlin") version "1.0.13"
}

val generatedSourcesDir = project.layout.buildDirectory.dir("generated/sources")

val generateModelInfoKotlinSource by
    tasks.registering(XsdKotlinGenTask::class) {
        description = "Generates Kotlin sources for ModelInfo classes."

        inputXsd.set(rootProject.file("schemas/model/modelinfo.xsd"))
        outputDir.set(generatedSourcesDir.map { it.dir("cql/commonMain/kotlin") })
        jsExport.set(false)
    }

val rawAntlrOutputDir = generatedSourcesDir.map { it.dir("antlr/commonMain/kotlin") }
val processedAntlrOutputDir = generatedSourcesDir.map { it.dir("antlr-processed/commonMain/kotln") }

val generateKotlinGrammarSource =
    tasks.register<AntlrKotlinTask>("generateKotlinGrammarSource") {
        dependsOn("cleanGenerateKotlinGrammarSource")
        source = fileTree("../grammar") { include("**/*.g4") }
        packageName = "org.cqframework.cql.gen"
        arguments = listOf("-visitor")
        outputDirectory =
            rawAntlrOutputDir.map { it.dir(packageName!!.replace(".", "/")) }.get().asFile
    }

val fixSuppressionsInGeneratedKotlinGrammarSource by
    tasks.registering(FixAntlrGeneratedSuppressions::class) {
        description = "Fix @Suppress annotations in Kotlin sources generated by ANTLR"

        dependsOn(generateKotlinGrammarSource)

        inputDir.set(rawAntlrOutputDir)
        outputDir.set(processedAntlrOutputDir)
    }

val inlineModelInfoXmls by
    tasks.registering(FilesToStringsTask::class) {
        inputFiles =
            mapOf(
                project.layout.projectDirectory
                    .file("src/commonMain/resources/org/hl7/elm/r1/system-modelinfo.xml")
                    .asFile to "systemModelInfoXml"
            )
        outputDir.set(
            project.layout.buildDirectory.dir(
                "generated/sources/inlineModelInfoXmls/commonMain/kotlin"
            )
        )
        packageName.set("org.hl7.cql.model")
        fileName.set("ModelInfoXmls.kt")
    }

kotlin {
    js { outputModuleName = "cql" }

    @OptIn(ExperimentalWasmDsl::class) wasmJs { outputModuleName = "cql" }

    sourceSets {
        commonMain {
            kotlin {
                srcDir(generateModelInfoKotlinSource)
                srcDir(fixSuppressionsInGeneratedKotlinGrammarSource)
                srcDir(inlineModelInfoXmls)
            }
            dependencies {
                api(project(":shared"))
                api("com.strumenta:antlr-kotlin-runtime:1.0.3")
            }
        }
        jvmMain { dependencies { api("com.strumenta:antlr-kotlin-runtime-jvm:1.0.3") } }
        jvmTest {
            dependencies {
                implementation(project(":quick"))
                implementation(project(":qdm"))
            }
        }
    }
}

dependencies { kover(project(":shared")) }
