// JAXB runtime deps needed for the classes generated by xjc
val xjcRuntimeDeps =
    listOf(
        "codes.rafael.jaxb2_commons:jaxb2-basics:3.0.0",
        "codes.rafael.jaxb2_commons:jaxb2-fluent-api:3.0.0",
        "jakarta.xml.bind:jakarta.xml.bind-api:4.0.1",
        "org.glassfish.jaxb:jaxb-runtime:4.0.3",
        "org.eclipse.persistence:org.eclipse.persistence.moxy:4.0.2",
    )
