import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

plugins {
    id("cql.xjc-conventions")
    id("cql.fhir-kotlin-multiplatform-conventions")
}

val generateFhirPathTests =
    tasks.register<XjcTask>("generateFhirPathTests") {
        outputDir.set(
            project.layout.buildDirectory.dir("generated/sources/engine-fhir/jvmTest/java")
        )
        schema.set("${projectDir}/src/jvmTest/resources/org/hl7/fhirpath/testSchema")
        extraArgs.set(listOf("-npa", "-p", "org.hl7.fhirpath.tests"))
    }

kotlin {
    js { outputModuleName = "engine-fhir" }

    @OptIn(ExperimentalWasmDsl::class) wasmJs { outputModuleName = "engine-fhir" }

    sourceSets {
        commonMain { dependencies { api(project(":engine")) } }

        jvmMain { dependencies { api(project(":ucum")) } }

        jvmTest {
            dependencies {
                implementation(libs.wiremock)
                implementation(project(":cql-to-elm"))
                implementation(project(":quick"))
                implementation(libs.hapi.fhir.client)

                // JAXB runtime deps needed for the classes generated by xjc
                implementation(libs.jaxb2.commons.basics)
                implementation(libs.jaxb2.commons.fluent.api)
                implementation(libs.jakarta.xml.bind.api)
                implementation(libs.jaxb.runtime)
                implementation(libs.moxy)
            }
        }
    }
}

java {
    sourceSets { named("jvmTest") { java { srcDir(generateFhirPathTests.map { it.outputDir }) } } }
}

dependencies { kover(project(":engine")) }
