// Generated by org.cqframework.cql.execution.Engine
(function() {
  var Context, Library, PatientSource, ctx, lib, measure, psource, result, _ref;

  _ref = require('./cql-exec'), Library = _ref.Library, Context = _ref.Context;

  PatientSource = require('./cql-patient').PatientSource;

  measure = require('./$MEASURE_SCRIPT$');

  lib = new Library(measure);

  importPackage(org.cqframework.cql.execution);
  psource = new TestPatientSource();
  //psource = new PatientSource([
  //  {
  //    "id": 1,
  //    "name": "John Smith",
  //    "gender": "M",
  //    "birthdate": "1980-02-17T06:15"
  //  }, {
  //    "id": 2,
  //    "name": "Sally Smith",
  //    "gender": "F",
  //    "birthdate": "2007-08-02T11:47"
  //  }
  //]);

  ctx = new Context(lib, psource);

  result = lib.exec(ctx);

  //console.log(JSON.stringify(result, void 0, 2));
  //print(JSON.stringify(result, void 0, 2));

  Results.add( JSON.stringify(result, void 0, 2) );

}).call(this);
