// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>QUICK.Model</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace QUICK.Model {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Address : Structure {
        
        private code useField;
        
        private @string textField;
        
        private List<@string> lineField;
        
        private @string cityField;
        
        private @string stateField;
        
        private @string zipField;
        
        private @string countryField;
        
        private Period periodField;
        
        public Address() {
            this.periodField = new Period();
            this.countryField = new @string();
            this.zipField = new @string();
            this.stateField = new @string();
            this.cityField = new @string();
            this.lineField = new List<@string>();
            this.textField = new @string();
            this.useField = new code();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public code use {
            get {
                return this.useField;
            }
            set {
                this.useField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public @string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("line", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public List<@string> line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public @string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public @string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public @string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public @string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public Period period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class code : Element {
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(uuid))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(oid))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(id))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Structure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Schedule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HumanName))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Contact))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Address))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SampledData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResourceReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Ratio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Range))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Quantity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Money))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Duration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Distance))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Count))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Age))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Period))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Identifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Coding))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CodeableConcept))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Attachment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(code))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(dateTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(date))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(uri))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@string))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(instant))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(base64Binary))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@decimal))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(integer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(boolean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Extension))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Element {
        
        private List<Extension> extensionField;
        
        private string idField;
        
        public Element() {
            this.extensionField = new List<Extension>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("extension", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public List<Extension> extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Extension : Element {
        
        private Element itemField;
        
        private string urlField;
        
        public Extension() {
            this.itemField = new Element();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("valueAddress", typeof(Address), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueAttachment", typeof(Attachment), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueBase64Binary", typeof(base64Binary), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueBoolean", typeof(boolean), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueCode", typeof(code), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueCodeableConcept", typeof(CodeableConcept), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueCoding", typeof(Coding), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueContact", typeof(Contact), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueDate", typeof(date), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueDateTime", typeof(dateTime), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueDecimal", typeof(@decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueHumanName", typeof(HumanName), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueIdentifier", typeof(Identifier), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueInstant", typeof(instant), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueInteger", typeof(integer), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valuePeriod", typeof(Period), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueQuantity", typeof(Quantity), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueRange", typeof(Range), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueRatio", typeof(Ratio), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueResource", typeof(ResourceReference), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueSampledData", typeof(SampledData), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueSchedule", typeof(Schedule), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueString", typeof(@string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("valueUri", typeof(uri), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Element Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Attachment : Type {
        
        private code contentTypeField;
        
        private code languageField;
        
        private base64Binary dataField;
        
        private uri urlField;
        
        private integer sizeField;
        
        private base64Binary hashField;
        
        private @string titleField;
        
        public Attachment() {
            this.titleField = new @string();
            this.hashField = new base64Binary();
            this.sizeField = new integer();
            this.urlField = new uri();
            this.dataField = new base64Binary();
            this.languageField = new code();
            this.contentTypeField = new code();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public code contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public code language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public base64Binary data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public uri url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public integer size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public base64Binary hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public @string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class base64Binary : Element {
        
        private byte[] valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class uri : Element {
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class integer : Element {
        
        private int valueField;
        
        private bool valueFieldSpecified;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class @string : Element {
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Structure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Schedule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HumanName))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Contact))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Address))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SampledData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResourceReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Ratio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Range))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Quantity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Money))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Duration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Distance))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Count))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Age))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Period))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Identifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Coding))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CodeableConcept))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Attachment))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public abstract partial class Type : Element {
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Schedule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HumanName))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Contact))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Address))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Structure : Type {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Schedule : Structure {
        
        private List<Period> eventField;
        
        private Repeat repeatField;
        
        public Schedule() {
            this.repeatField = new Repeat();
            this.eventField = new List<Period>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("event", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public List<Period> @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Repeat repeat {
            get {
                return this.repeatField;
            }
            set {
                this.repeatField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Period : Type {
        
        private dateTime startField;
        
        private dateTime endField;
        
        public Period() {
            this.endField = new dateTime();
            this.startField = new dateTime();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public dateTime start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public dateTime end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class dateTime : Element {
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Repeat {
        
        private integer frequencyField;
        
        private code whenField;
        
        private @decimal durationField;
        
        private code unitsField;
        
        private integer countField;
        
        private dateTime endField;
        
        public Repeat() {
            this.endField = new dateTime();
            this.countField = new integer();
            this.unitsField = new code();
            this.durationField = new @decimal();
            this.whenField = new code();
            this.frequencyField = new integer();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public integer frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public code when {
            get {
                return this.whenField;
            }
            set {
                this.whenField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public @decimal duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public code units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public integer count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public dateTime end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class @decimal : Element {
        
        private decimal valueField;
        
        private bool valueFieldSpecified;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class HumanName : Structure {
        
        private code useField;
        
        private @string textField;
        
        private List<@string> familyField;
        
        private List<@string> givenField;
        
        private List<@string> prefixField;
        
        private List<@string> suffixField;
        
        private Period periodField;
        
        public HumanName() {
            this.periodField = new Period();
            this.suffixField = new List<@string>();
            this.prefixField = new List<@string>();
            this.givenField = new List<@string>();
            this.familyField = new List<@string>();
            this.textField = new @string();
            this.useField = new code();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public code use {
            get {
                return this.useField;
            }
            set {
                this.useField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public @string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("family", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public List<@string> family {
            get {
                return this.familyField;
            }
            set {
                this.familyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("given", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public List<@string> given {
            get {
                return this.givenField;
            }
            set {
                this.givenField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("prefix", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public List<@string> prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("suffix", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public List<@string> suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public Period period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Contact : Structure {
        
        private code systemField;
        
        private @string valueField;
        
        private code useField;
        
        private Period periodField;
        
        public Contact() {
            this.periodField = new Period();
            this.useField = new code();
            this.valueField = new @string();
            this.systemField = new code();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public code system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public @string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public code use {
            get {
                return this.useField;
            }
            set {
                this.useField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Period period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class SampledData : Type {
        
        private Quantity originField;
        
        private @decimal periodField;
        
        private @decimal factorField;
        
        private @decimal lowerLimitField;
        
        private @decimal upperLimitField;
        
        private integer dimensionsField;
        
        private @string dataField;
        
        public SampledData() {
            this.dataField = new @string();
            this.dimensionsField = new integer();
            this.upperLimitField = new @decimal();
            this.lowerLimitField = new @decimal();
            this.factorField = new @decimal();
            this.periodField = new @decimal();
            this.originField = new Quantity();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Quantity origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public @decimal period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public @decimal factor {
            get {
                return this.factorField;
            }
            set {
                this.factorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public @decimal lowerLimit {
            get {
                return this.lowerLimitField;
            }
            set {
                this.lowerLimitField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public @decimal upperLimit {
            get {
                return this.upperLimitField;
            }
            set {
                this.upperLimitField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public integer dimensions {
            get {
                return this.dimensionsField;
            }
            set {
                this.dimensionsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public @string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Money))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Duration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Distance))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Count))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Age))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Quantity : Type {
        
        private @decimal valueField;
        
        private code comparatorField;
        
        private @string unitsField;
        
        private uri systemField;
        
        private code codeField;
        
        public Quantity() {
            this.codeField = new code();
            this.systemField = new uri();
            this.unitsField = new @string();
            this.comparatorField = new code();
            this.valueField = new @decimal();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public @decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public code comparator {
            get {
                return this.comparatorField;
            }
            set {
                this.comparatorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public @string units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public uri system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public code code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Money : Quantity {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Duration : Quantity {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Distance : Quantity {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Count : Quantity {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Age : Quantity {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class ResourceReference : Type {
        
        private @string referenceField;
        
        private @string displayField;
        
        public ResourceReference() {
            this.displayField = new @string();
            this.referenceField = new @string();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public @string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public @string display {
            get {
                return this.displayField;
            }
            set {
                this.displayField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Ratio : Type {
        
        private Quantity numeratorField;
        
        private Quantity denominatorField;
        
        public Ratio() {
            this.denominatorField = new Quantity();
            this.numeratorField = new Quantity();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Quantity numerator {
            get {
                return this.numeratorField;
            }
            set {
                this.numeratorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Quantity denominator {
            get {
                return this.denominatorField;
            }
            set {
                this.denominatorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Range : Type {
        
        private Quantity lowField;
        
        private Quantity highField;
        
        public Range() {
            this.highField = new Quantity();
            this.lowField = new Quantity();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Quantity low {
            get {
                return this.lowField;
            }
            set {
                this.lowField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Quantity high {
            get {
                return this.highField;
            }
            set {
                this.highField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Identifier : Type {
        
        private uri systemField;
        
        private @string idField;
        
        public Identifier() {
            this.idField = new @string();
            this.systemField = new uri();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public uri system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public @string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class Coding : Type {
        
        private uri systemField;
        
        private @string versionField;
        
        private code codeField;
        
        private @string displayField;
        
        private boolean primaryField;
        
        private uri valueSetField;
        
        public Coding() {
            this.valueSetField = new uri();
            this.primaryField = new boolean();
            this.displayField = new @string();
            this.codeField = new code();
            this.versionField = new @string();
            this.systemField = new uri();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public uri system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public @string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public code code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public @string display {
            get {
                return this.displayField;
            }
            set {
                this.displayField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public boolean primary {
            get {
                return this.primaryField;
            }
            set {
                this.primaryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public uri valueSet {
            get {
                return this.valueSetField;
            }
            set {
                this.valueSetField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class boolean : Element {
        
        private bool valueField;
        
        private bool valueFieldSpecified;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class CodeableConcept : Type {
        
        private List<Coding> codingField;
        
        private @string textField;
        
        public CodeableConcept() {
            this.textField = new @string();
            this.codingField = new List<Coding>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("coding", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public List<Coding> coding {
            get {
                return this.codingField;
            }
            set {
                this.codingField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public @string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class date : Element {
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class instant : Element {
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class uuid : Element {
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class oid : Element {
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hl7.org/fhir")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://hl7.org/fhir", IsNullable=false)]
    public partial class id : Element {
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
